PROGS_CXX = \
  basic basic_threaded binary_data binary_data_publish \
  data_types jitter_test lpush_benchmark multi-client pub_sub \
  speed_test_async speed_test_async_multi speed_test_pubsub speed_test_sync

SRCS_basic                  = basic.cpp
SRCS_basic_threaded         = basic_threaded.cpp
SRCS_binary_data            = binary_data.cpp
SRCS_binary_data_publish    = binary_data_publish.cpp
SRCS_data_types             = data_types.cpp
SRCS_jitter_test            = jitter_test.cpp
SRCS_lpush_benchmark        = lpush_benchmark.cpp
SRCS_multi-client           = multi-client.cpp
SRCS_pub_sub                = pub_sub.cpp
SRCS_speed_test_async       = speed_test_async.cpp
SRCS_speed_test_async_multi = speed_test_async_multi.cpp
SRCS_speed_test_pubsub      = speed_test_pubsub.cpp
SRCS_speed_test_sync        = speed_test_sync.cpp

MK_MAN   = no
NO_OBJ   = noobj

CXXFLAGS = -g
CXXFLAGS += -pthread
CXXFLAGS += -std=c++11 -pedantic
CXXFLAGS += -Wall -Wextra
CXXFLAGS += -I/usr/local/include

LDFLAGS += -L/usr/local/lib64 -lredox -L/usr/local/lib -lev

.include <bsd.progs.mk>
